-- MySQL Script generated by MySQL Workbench
-- Sat Apr  4 21:06:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Helping_UCIs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Helping_UCIs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Helping_UCIs` DEFAULT CHARACTER SET utf8 ;
USE `Helping_UCIs` ;

-- -----------------------------------------------------
-- Table `Helping_UCIs`.`Dimero_D`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helping_UCIs`.`Dimero_D` (
  `IdPaciente` INT NOT NULL,
  `Dimero_D` DOUBLE NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  CONSTRAINT `IdPaciente`
    FOREIGN KEY (`IdPaciente`)
    REFERENCES `Helping_UCIs`.`Pacientes` (`IdPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `Helping_UCIs`.`Ferritina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helping_UCIs`.`Ferritina` (
  `IdPaciente` INT NOT NULL,
  `Ferritina` DOUBLE NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  CONSTRAINT `IdPaciente2`
    FOREIGN KEY (`IdPaciente`)
    REFERENCES `Helping_UCIs`.`Pacientes` (`IdPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `Helping_UCIs`.`Fibrinogeno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helping_UCIs`.`Fibrinogeno` (
  `IdPaciente` INT NOT NULL,
  `Fibrinogeno` DOUBLE NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  CONSTRAINT `IdPaciente3`
    FOREIGN KEY (`IdPaciente`)
    REFERENCES `Helping_UCIs`.`Pacientes` (`IdPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `Helping_UCIs`.`Fibrinogeno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helping_UCIs`.`Fibrinogeno` (
  `IdPaciente` INT NOT NULL,
  `Fibrinogeno` DOUBLE NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  CONSTRAINT `IdPaciente4`
    FOREIGN KEY (`IdPaciente`)
    REFERENCES `Helping_UCIs`.`Pacientes` (`IdPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `Helping_UCIs`.`Linfocitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helping_UCIs`.`Linfocitos` (
  `IdPaciente` INT NOT NULL,
  `Linfocitos` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  CONSTRAINT `IdPaciente5`
    FOREIGN KEY (`IdPaciente`)
    REFERENCES `Helping_UCIs`.`Pacientes` (`IdPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `Helping_UCIs`.`Pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helping_UCIs`.`Pacientes` (
  `IdPaciente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(58) NOT NULL,
  `Apellidos` VARCHAR(70) NOT NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  `Tipo_Doc` VARCHAR(9) NULL DEFAULT NULL,
  `Num_Doc` VARCHAR(20) NULL DEFAULT NULL,
  `Num_Otro_Doc` VARCHAR(30) NULL DEFAULT NULL,
  `Genero` VARCHAR(6) NOT NULL,
  `Peso` DOUBLE NOT NULL,
  `Altura` DOUBLE NOT NULL,
  `Fecha_Llegada` DATE NOT NULL,
  `Fecha_Comienzo_Sint` DATE NOT NULL,
  `Necesidad_Respirador` TINYINT(1) NOT NULL,
  `Patologias_Previas` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`IdPaciente`));



-- -----------------------------------------------------
-- Table `Helping_UCIs`.`Presion_arterial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helping_UCIs`.`Presion_arterial` (
  `IdPaciente` INT NOT NULL,
  `Presion_Sistolica` DOUBLE NOT NULL,
  `Presion_diastolica` DOUBLE NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  CONSTRAINT `IdPaciente6`
    FOREIGN KEY (`IdPaciente`)
    REFERENCES `Helping_UCIs`.`Pacientes` (`IdPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `Helping_UCIs`.`Proteina_C`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helping_UCIs`.`Proteina_C` (
  `IdPaciente` INT NOT NULL,
  `Proteina_C` DOUBLE NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  CONSTRAINT `IdPaciente7`
    FOREIGN KEY (`IdPaciente`)
    REFERENCES `Helping_UCIs`.`Pacientes` (`IdPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `Helping_UCIs`.`RX_Torax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helping_UCIs`.`RX_Torax` (
  `IdPaciente` INT NOT NULL,
  `Sin_Lesiones` TINYINT(1) NULL DEFAULT 0,
  `Unilateral` INT NULL DEFAULT NULL,
  `Bilateral_b+b` TINYINT(1) NULL DEFAULT 0,
  `Bilateral_b+c` TINYINT(1) NULL DEFAULT 0,
  `Bilateral_c+c` TINYINT(1) NULL DEFAULT 0,
  `N_Campos_Pulmonares_Afectados` INT NULL DEFAULT NULL,
  `Otras` VARCHAR(50) NULL DEFAULT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Observaciones` VARCHAR(500) NULL DEFAULT NULL,
  CONSTRAINT `IdPaciente8`
    FOREIGN KEY (`IdPaciente`)
    REFERENCES `Helping_UCIs`.`Pacientes` (`IdPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `Helping_UCIs`.`Saturacion_Oxigeno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helping_UCIs`.`Saturacion_Oxigeno` (
  `IdPaciente` INT NOT NULL,
  `Sat_O2` DOUBLE NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  CONSTRAINT `IdPaciente9`
    FOREIGN KEY (`IdPaciente`)
    REFERENCES `Helping_UCIs`.`Pacientes` (`IdPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `Helping_UCIs`.`Temperatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helping_UCIs`.`Temperatura` (
  `IdPaciente` INT NOT NULL,
  `Temperatura` DOUBLE NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  CONSTRAINT `IdPaciente10`
    FOREIGN KEY (`IdPaciente`)
    REFERENCES `Helping_UCIs`.`Pacientes` (`IdPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
